src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @Vich\Uploadable()
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;

    /**
     * @ORM\Column(type="datetime", options={"default": "1000-01-01 00:00:00"})
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contenu;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="categ")
     */
    private $LaCategorie;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getFilename(): ?string
    {
        return $this->filename;
    }
    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;
        return $this;
    }
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getLaCategorie(): ?Categorie
    {
        return $this->LaCategorie;
    }

    public function setLaCategorie(?Categorie $LaCategorie): self
    {
        $this->LaCategorie = $LaCategorie;

        return $this;
    }
    public function __toString()
    {
        return $this->LaCategorie;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Form\SearcheType;
use App\Repository\ArticleRepository;
use App\Repository\TestImageRepository;
use MongoDB\Driver\Manager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Asset\Package;
use Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy;
use App\Form\AjoutMajType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormTypeInterface;
use App\Form\EditContenuType;
use App\Entity\ContenuArticle;
use App\Twig\AppExtension;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Response;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function home(ArticleRepository $repo,TestImageRepository $repo1)
    {
        $images=$repo1->findAll();
        $articles = $this->getDoctrine()
        ->getRepository(Article::class)
        ->findByDate();
        return $this->render('main/home.html.twig', [
            'controller_name' => 'MainController','articles'=>$articles,'images'=>$images
        ]);
    }
    /**
     * @Route("/vieAssos", name="vieAssociative")
     */
    public function vieAssociative(ArticleRepository $repo,TestImageRepository $repo1)
    {
        $articles=$repo->findAll();
        $images=$repo1->findAll();
        return $this->render('main/vieAssociative.html.twig', [
            'controller_name' => 'MainController','articles'=>$articles,'images'=>$images
        ]);
    }
    /**
     * @Route("/actualites", name="actualites")
     */
    public function ShowActualites( Article $article=null,ArticleRepository $repo,TestImageRepository $repo1,Request $request)
    {
        $images=$repo1->findAll();


            $form =$this->createForm(SearcheType::class,$article);
            $form->handleRequest($request);
        $articles = $this->getDoctrine();
        $title = $form['title']->getData();
        if($form->isSubmitted()&&$form->isValid()) {
            dump($articles);
            $articles = $this->getDoctrine()
                ->getRepository(Article::class)
                ->findEntitiesByString($title);


            return $this->render('main/actualites.html.twig', [
                'controller_name' => 'MainController','articles'=>$articles,'images'=>$images,'formSearch'=>$form->createView()]);
        }
        return $this->render('main/actualites.html.twig', [
            'controller_name' => 'MainController','articles'=>$articles,'images'=>$images,'formSearch'=>$form->createView()
        ]);
    }
    /**
     * @Route("/actualitesTag", name="actualitesTag")
     */
    public function ShowActualitesTag( Article $article=null,ArticleRepository $repo,TestImageRepository $repo1,Request $request)
    {
        $images=$repo1->findAll();
        $articles = $this->getDoctrine();
        $categorie =$request->query->get('LaCategorie');
            dump($articles);
            $articles = $this->getDoctrine()
                ->getRepository(Article::class)
                ->findEntitiesByString($categorie);

        return $this->render('main/actualites.html.twig', [
            'controller_name' => 'MainController','articles'=>$articles,'images'=>$images
        ]);
    }
    /**
     * @Route("/card", name="card")
     */
    public function ShowCard(ArticleRepository $repo,TestImageRepository $repo1)
    {
        $articles=$repo->findAll();
        $images=$repo1->findAll();
        return $this->render('main/card.html.twig', [
            'controller_name' => 'MainController','articles'=>$articles,'images'=>$images
        ]);
    }
    /**
     * @Route("main/show/{id}", name="blog_show")
     */
    public  function  show(Article $article,Request $request,ArticleRepository $repo,TestImageRepository $repo1)
    {
        $articles=$repo->findAll();
        $images=$repo1->findAll();
       return $this->render('main/show.html.twig',['article'=>$article,'articles'=>$articles,'images'=>$images]);
    }
    /**
     * @Route("main/error", name="error")
     */
    /*public  function  error()
    {
        return $this->render('main/Erreur.html.twig');
    }

    /**
     * Creates a new ActionItem entity.
     *
     * @Route("/search", name="ajax_search")
     * @Method("GET")
     */
   /* public function searchAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $requestString = $request->get('q');
        $entities =  $em->getRepository('App:Article')->findEntitiesByString($requestString);
        if(!$entities) {
            $result['entities']['error'] = "keine Einträge gefunden";
        } else {
            $result['entities'] = $this->getRealEntities($entities);
        }
        return new Response(json_encode($result));
    }
    public function getRealEntities($entities){
        foreach ($entities as $entity){
            $realEntities[$entity->getId()] = $entity->getTitle();
        }
        return $realEntities;
    }*/
}

?>

templates/main/Erreur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
 <article  class="container" style="background:url('../img/error.jpg')no-repeat center; background-size:cover;width: 1000px;height: 1000px">

 </article>
{% endblock %}

templates/main/actualites.html.twig
{% extends 'base.html.twig' %}
{% form_theme formSearch  'bootstrap_4_layout.html.twig' %}


{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark  lighten-3 mb-4 BackBleuUSV" >
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="form-inline mr-autoform-control" type="text" placeholder="Search" aria-label="Search">
                {{ form_start(formSearch) }}

                {{ form_row(formSearch.title, {'attr': {'placeholder': ""}}) }}

                <i class="fas fa-search text-white ml-3" aria-hidden="true"></i>
                <a type="submit" value="hassan" class="btn btn-success" href="{{ path('actualites') }}">Les Compétitions</a>

                <button class="btn btn-success">Vie Associative</button>

                {{ form_end(formSearch) }}


                <div class="md-form my-0 text-light click">
                </div>
            </div>
        </div>
    </nav>

    <div style="">
        <div class=" ">
            <h1 class="text-center pt-5 ">actualité corepondant à votre recherche</h1>
        </div>
        <div class="d-flex flex-wrap flex-row justify-content-around" >
            {% for article in articles %}
                <div class="card mb-5" style="max-height: 650px; min-height: 650px; max-width: 450px">
                    <img class="card-img-top" src="{{ asset('images/' ~ article.filename) }}" alt="Card image cap" style="max-height: 300px; max-width: 600px">
                    <div class="font-weight-bold "> ecrit le {{ article.updatedAt | date('d/m/y') }} à   {{ article.updatedAt | date('H:i') }}</div>
                    <div class="card-body">
                        <h4 class="card-title font-weight-bold">{{ article.title }}</h4>
                        <p class="card-text">{{ article.contenu }}</p>
                        <div class="d-flex justify-content-center">
                            <a class="btn btn-primary  btn-rounded" href="{{ path('blog_show',{'id':article.id}) }}">Lire plus</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


    </div>
{% endblock %}

templates/main/card.html.twig
<div class=" d-flex justify-content flex-wrap">
    {% for article in articles %}
        <div class="card mb-2 mx-auto" style="max-height: 600px; min-height: 600px">
            <img class="card-img-top" src="{{ asset('images/' ~ article.filename) }}" alt="Card image cap" style="max-height: 300px;">
            <div class="font-weight-bold "> ecrit le {{ article.updatedAt | date('d/m/y') }} à   {{ article.updatedAt | date('H:i') }}</div>
            <div class="card-body">
                <h4 class="card-title font-weight-bold">{{ article.title }}</h4>
                <p class="card-text">{{ article.contenu }}</p>
                <div class="d-flex justify-content-center">
                    <a class="btn btn-primary  btn-rounded" href="{{ path('blog_show',{'id':article.id}) }}">Lire plus</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/main/footer.html.twig
{% extends 'base.html.twig' %}
{% block footer %}
    {{ parent() }}
{% endblock %}

templates/main/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
    <div style="height: 800px">
        <div class=" " style="background-color: rgb(244,244,244);">
            <h1 class="text-center pt-5 ">Les actualités récentes</h1>
        </div>
        <div class="carousel-wrapper rgb">
            <div class="carousel align-items-center" data-flickity>
                {% for article in articles %}
                <div class="carousel-cell">
                    <div class="card mb-2" style="max-height: 600px; min-height: 600px">
                        <img class="card-img-top" src="{{ asset('images/' ~ article.filename) }}" alt="Card image cap" style="max-height: 300px;">
                        <div class="font-weight-bold "> ecrit le {{ article.updatedAt | date('d/m/y') }} à   {{ article.updatedAt | date('H:i') }}</div>
                        <div class="card-body">
                            <h4 class="card-title font-weight-bold">{{ article.title }}</h4>
                            <p class="card-text">{{ article.contenu }}</p>
                            <div class="d-flex justify-content-center">
                                <a class="btn btn-primary  btn-rounded" href="{{ path('blog_show',{'id':article.id}) }}">Lire plus</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}
 {{ parent() }}
{% block title %}Hello MainController!{% endblock %}

{% block body %}

{% endblock %}

templates/main/logo110.html.twig
{% extends 'base.html.twig' %}

{% block logo %}
    {{ parent() }}

{% endblock %}

templates/main/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
    <section class=" d-flex justify-content-center container z-depth-1 my-3 ">
            <article class=" d-flex justify-content-center flex-column my-3 px-5">
                <h2 class="text-center">{{ article.title }}</h2>
                <p class="  text-left date "> publié le {{ article.updatedAt | date('d/m/y') }} à   {{ article.updatedAt | date('H:i') }}</p>
                <div class="styleOne"></div>
                <img class="mx-auto img-fluid" src="{{ asset('images/' ~ article.filename) }}" alt="">
                    <p class="">{{ article.content | raw }}</p>
                    <div class="styleOne"></div>
                    <h2 class="text-center mx-auto">Cliquer ici pour revenir au début</h2>
                    <a class="btn btn-primary w-25 mx-auto" href="{{ path("home") }}"><i class="fas fa-undo-alt"></i></a>
            </article>
    </section>
    <div class="z-depth-3  scroll-top d-flex justify-content-center align-self-center " data-scroll="up" >
        <i class="fa fa-chevron-up my-auto"></i>
    </div>
{% endblock %}

templates/main/vieAssociative.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
    <div class="logoContainer py-3">
        <h1 class="text-uppercase font-weight-bold Bureau text-center w-responsive animated bounceIn wow">bureau</h1>
        <div class="d-flex justify-content-center py-3 align-items-center flex-wrap container-fluid organigram" >
            <div class="animated bounceInLeft wow">
                <h5 class="text-uppercase font-weight-bold text-white text-right">Ribeyre</h5>
                <h5 class=" font-weight-bold text-white text-right">Philipe</h5>
                <p class="text-white text-right">Président</p>
            </div>
            <div class="contourAdmin mx-3 z-depth-2 animated bounceIn  wow ">
                <div class="d-flex justify-content-center imgAdmin animated"><img class="img-fluid  animated " srcset="{{ asset('PhotoConseil/Philipe.png') }} "></div>
                <div >
                    <div class="RUSV  ">

                    </div >
                    <div class="JUSV  ">

                    </div>
                    <div class="VUSV  ">

                    </div>
                </div>
            </div>
                <img class="usv_logo moncercle img-fluid animated bounceIn wow" src="{{ asset('usv_logo.png') }}"  >
            <div class="contourAdmin mx-3 z-depth-2 animated bounceIn wow">
                <div class="imgAdmin animated  d-flex justify-content-center animated "><img class="img-fluid animated" src="{{ asset('PhotoConseil/Henry.png') }}"></div>
                <div>
                    <div class="RUSV">

                    </div >
                    <div class="JUSV">

                    </div>
                    <div class="VUSV">

                    </div>
                </div>
            </div>
            <div  class="animated bounceInRight wow">
                <h5 class="text-uppercase font-weight-bold text-white text-left">Vuillet</h5>
                <h5 class="font-weight-bold text-white text-left">Henri</h5>
                <p class="text-white text-left">Vice-Président<br>Secretaire</p>
            </div>
        </div>
        <div class="contourAdmin mx-auto z-depth-2 animated bounceIn wow">
            <div class="imgAdmin animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Anthony.png') }}"></div>
            <div class="">
                <div class="RUSV">

                </div >
                <div class="JUSV">

                </div>
                <div class="VUSV">

                </div>
            </div>
        </div>
        <div class=" d-flex justify-content-center organigram">
            <div class="mx-auto animated bounceInUp wow">
                <h5 class="text-uppercase font-weight-bold text-white text-center">Guizon</h5>
                <h5 class=" font-weight-bold text-white text-center">Anthony</h5>
                <p class="text-white text-center">Trésorier</p>
            </div>

        </div>
    </div>
    <h1 class="text-uppercase font-weight-bold ConseilAd text-center text-white w-responsive my-3 animated bounceIn wow ">Conseil D'administration</h1>
    <div class="d-flex flex-row justify-content-around flex-wrap">
        <div class="py-3 ">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceInLeft  wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Roland.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 animated bounceInUp wow textA2">
                <p>BERNERD<br>
                Roland</p>
            </div>
            <div class="cercleTierC mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">C3</h4>
            </div>
        </div>
        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceInLeft  wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Hassan.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 animated bounceInUp wow textA2">
                <p>EL BELGHITI<br>
               Hassan</p>
            </div>
            <div class="cercleTierC mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">C2</h4>
            </div>
        </div>
        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceInLeft  wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Cristophe.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 bounceInUp wow textA2">
                <p>ENJOLRAS<br>
                Cristophe</p>
            </div>
            <div class="cercleTierA mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">A3</h4>
            </div>
        </div>
        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceInLeft  wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Jean_Paul.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 bounceInUp wow textA2">
                <p>GORY<br>
               Jean-Paul</p>
            </div>
            <div class="cercleTierB mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">B3</h4>
            </div>
        </div>
        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceIn wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Jean_Louis.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 bounceInUp wow textA2">
                <p>GOUTEREDONDE<br>
                Jean-Louis</p>
            </div>
            <div class="cercleTierB mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">B2</h4>
            </div>
        </div>

        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceInRight wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Anthony2.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 bounceInUp wow textA2">
                <p>GUIZON<br>
               Anthony</p>
            </div>
            <div class="cercleTierB mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">B1</h4>
            </div>
        </div>
        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceInRight wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Philipe2.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 bounceInUp wow textA2">
                <p>RIBEYRE<br>
                Philipe</p>
            </div>
            <div class="cercleTierA mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">A1</h4>
            </div>
        </div>
        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated bounceInRight wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Alain.png') }}"></div>
                <div class="BUSV">

                </div >
            </div>
            <div class="text-center text-dark pt-3 bounceInUp wow textA2">
                <p >VERGEZAC<br>
               Alain</p>
            </div>
            <div class="cercleTierC mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">C1</h4>
            </div>
        </div>
        <div class="py-3">
            <div class="contourAdmin2 mx-auto z-depth-2 animated  bounceInRight wow">
                <div class="imgAdmin2 animated  d-flex justify-content-center"><img class="img-fluid self" src="{{ asset('PhotoConseil/Henry2.png') }}"></div>
                <div class="BUSV">

                </div>
            </div>
            <div class="text-center text-dark pt-3 bounceInUp wow textA2">
                <p>VUILLET<br>
                Henri</p>
            </div>
            <div class="cercleTierA mx-auto animated bounceIn wow z-depth-2">
                <h4 class="text-white font-weight-bold text-uppercase my-auto">A2</h4>
            </div>
        </div>
    </div>
    <div class=" d-flex flex-row justify-content-end tierMin ">
        <div class="cercleTierAmin animated bounceIn wow z-depth-2"></div>
        <p class="ml-2 mr-5 animated bounceIn wow ">Sièges Tier A</p>
        <div class="cercleTierBmin animated bounceIn wow z-depth-2"></div>
        <p class="ml-2 mr-5 animated bounceIn wow ">Sièges Tier B</p>
        <div class="cercleTierCmin animated bounceIn wow z-depth-2"></div>
        <p class="ml-2 mr-5 animated bounceIn wow ">Sièges Tier C</p>
    </div>
{% endblock %}